### ISSUE TITLE
Empty dictionary declaration

### ISSUE THREAD

**Issue by danielgomezrico** [ksm/SwiftInFlux#77] opened 2015-02-11 12:48 UTC
The next line is not working in beta 6.3 XCode. 

`
let error: NSError
var newUserInfo = error.userInfo as? [NSObject: NSObject] ?? [:]
`

**Comment by radex** [comment] 2015-02-11 13:01
SwiftInFlux is not a list of bugs in Swift.

**Comment by danielgomezrico** [comment] 2015-02-11 19:33
That shows a change on the compiler/IDE not a bug.

**Comment by radex** [comment] 2015-02-11 19:38
I don't think I understand.

**Comment by danielgomezrico** [comment] 2015-02-11 22:05
I had that line compiling in XCode 6.1 but it marks as an error in XCode 6.3 beta
`Expected experssion for size of array type`

and if you add some parentesis it compile:
`let newUserInfo = (error.userInfo as? [NSObject:NSObject]) ?? [:]`

Still not the objective of SwiftInFlux?

**Comment by jklausa** [comment] 2015-02-11 22:10
Ultimately, no. 

This seems like a regression in a compiler, and I believe you should definitely file a radar about that, but that doesn't look like a deliberate change in the language semantics to me.

**Comment by radex** [comment] 2015-02-11 22:11
Hm. It looks like the `as?` operator has changed its precedence (it's now lower than `??`) — I checked and `??` has the same precedence as before.

I dunno, it is a change, but I would never make the assumption that `error.userInfo as? [NSObject: NSObject] ?? [:] ` did what you expected to. I'd put it in parens anyway.

@jklausa? @ksm?

**Comment by jklausa** [comment] 2015-02-11 22:13
Oh, snap, right, the precedence did change. Totally forgot about it! I'm not so sure myself now.

**Comment by radex** [comment] 2015-02-13 07:41
Turns out, it is a bug :)

https://devforums.apple.com/message/1102772#1102772

Should be fixed in the next beta.

**Closed by radex** 2015-02-13 07:41 UTC
